### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by florian-jackisch** [nfode/latex-formatter#4]
Using the `latex-formatter` plugin on a Mac with macOS Sierra results in the message `Your os is not supported!`. I have the latexindent script installed and in my $PATH. Are there any plans to support macOS in the future?

**Comment by nfode** [comment]
I don't have a mac to test but i published a new version. You can try if it works. 
Please give me feedback if you test!

**Comment by florian-jackisch** [comment]
Thank you @nfode. Your reply was super fast and the new release works like a charm!

**Comment by nfode** [comment]
How do you have installed latexindent.pl? With the linux guide?
